### ISSUE TITLE
configure ANNOVAR DBs for VIC

### ISSUE THREAD

**Issue by MTZimmer** [HGLab/VIC#1]
I am testing ANNOVAR and you have it setup to look for the cosmic84_coding library.  I have cosmic90 setup and in the humandb directory with the rest of the required files. However, when I run VIC, it says it cannot find cosmic84. How do I configure VIC to use my cosmic90 file?

**Comment by maxh190** [comment]
VIC doesn't have any configuration file.  You may need to change the configure part of ANNOVAR so that it uses cosmic90 according to its guidelines.
________________________________

**Comment by MTZimmer** [comment]
Thank you for your reply. As far as I can see, it appears that you have hard-coded the ANNOVAR commands.

Context: To run ANNOVAR, I would do:
`table_annovar.pl ./VIC/example/vic_test4.vcf ${annovar}/humandb/ -buildver hg19 -out test4_cosmic -remove -protocol cosmic90 -operation f`
to annotate a VCF file with the cosmic90 db. I am not accustomed to ANNOVAR having a configuration file. Perhaps there are distributions of ANNOVAR that have a wrapper with config, but I am not aware of them.

I just looked through your VIC/src/main/java/vic/VIC.java and you appear to have it hard-coded in multiple places as:
`String ds = "refGene esp6500siv2_all 1000g2015aug avsnp150 dbnsfp35a clinvar_20190305 exac03 dbscsnv11 dbnsfp31a_interpro ensGene knownGene cosmic84_coding icgc21 gnomad211_exome";`

and elsewhere, such as,
`cmd = "perl " + tableannovar + " " + inputfile + " " + database_humandb + " -buildver " + buildver + "  -outfile " + outputfile
                        + " -remove -protocol refGene,ensGene,knownGene,esp6500siv2_all,1000g2015aug_all,exac03,avsnp150,dbnsfp35a,dbscsnv11,"
                        + "dbnsfp31a_interpro,clinvar_20190305,cosmic84_coding,icgc21,gnomad211_exome  -operation  g,g,g,f,f,f,f,f,f,f,f,f,f,f  -nastring .  "`

Any recommendations as to how to update VIC with respect to different ANNOVAR resources would be appreciated.

**Comment by maxh190** [comment]
I just changed a little bit of the source code of VIC so that you can specify your cosmic version as follows

-cosmic cosmic90  or  --cosmic_version cosmic90

________________________________

**Comment by MTZimmer** [comment]
Thank you.
I see that you added input flags for 4 ANNOVAR databases. Consider that users may need to, over time, update more/other ANNOVAR databases. To ensure VIC has a long-standing value, you may want to make a more scalable way to setup the full ANNOVAR command. Something like making the whole -operation and -protocol strings as optional inputs.
