### ISSUE TITLE
Command Error

### ISSUE THREAD

**Issue by dcharrance** [HGLab/VIC#1]
Hi Max,
Command: 
java -jar /home/dcharrance/VIC/target/VIC-1.0.1.jar -annotate_variation /home/dcharrance/annovar/annotate_variation.pl -b hg19 -convert2annovar /home/dcharrance/annovar/convert2annovar.pl -table_annovar /home/dcharrance/annovar/table_annovar.pl -d /home/dcharrance/annovar/humandb -db /home/dcharrance/VIC/vicdb -i vic_test1.avinput -input_type avinput -o prova_vic.vic.

Output: 
Warning: The VIC seems not run correctly, please check your inputs , options and configure file!
Error: The VIC did not find the annotation result file from ANNOVAR!
Error: The name of annotation result file should be like prova_vic.vic.<*sample_name*>.hg19_multianno.txt

Have you seen this error before?

Thanks

Debora

**Comment by zhaohh52** [comment]
Hi，I had the same problem. Did you solved it? How ？Thank U.
