### ISSUE TITLE
Exception in thread "main" java.lang.NumberFormatException:

### ISSUE THREAD

**Issue by dcharrance** [HGLab/VIC#2]
Hi Max,
with the command: 
java -jar /swf/VIC-main/target/VIC-1.0.1.jar -annotate_variation /swf/annovar/annotate_variation.pl -b hg38 -convert2annovar /swf/annovar/convert2annovar.pl -table_annovar /swf/annovar/table_annovar.pl -d /swf/annovar/humandb -db /swf/VIC-main/vicdb -i SG_PD-7107_P_final.vcf  -input_type vcf -output prova_vic

I've obtained the following errors:
Exception in thread "main" java.lang.NumberFormatException: For input string: "chr1"
at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
at java.base/java.lang.Double.parseDouble(Double.java:543)
at vic.VIC.Check_Mut(VIC.java:1496)
at vic.VIC.Assign(VIC.java:1802)
at vic.VIC.My_Cancer_var_can(VIC.java:2038)
at vic.VIC.main(VIC.java:372)

and

Warning: The VIC seems not run correctly, please check your inputs , options and configure file!
Error: The VIC did not find the annotation result file from ANNOVAR!
Error: The name of annotation result file should be like prova_vic.<*sample_name*>.hg38_multianno.txt

Can you help me?
Thanks
Debora

**Comment by dcharrance** [comment]
Hi Max,
I wrote you a few days ago about some problems I encountered using VIC. Can you help me?
Thank you
Debora

**Comment by maxh190** [comment]
Hi Debora,

As I mentioned earlier, it was impractical to implement those functions,
including Check_VF, Check_PotG and Check_Pubs, programmatically when we
developed VIC.  They are not supported.  You may find that not all of the
functions recommended by AMP-ASCO-CAP 2017 Guidelines can be implemented in
a program from the VIP paper.

Do you have any problems with using the available functions of the VIC?

Thanks,
Max

**Comment by dcharrance** [comment]
Hi Max,
I used the command that I found in the readme. I didn't use intentionally the functions Check_VF, Check_PotG and Check_Pubs. How can I do to not use them?

Thanks for your answer.

Debora

**Comment by maxh190** [comment]
Do you mean you could not run the analysis on the testing dataset?  Copy
the command that you used to me so that I can test it.

**Comment by dcharrance** [comment]
No, the analysis on the testing dataset run correctly. The problems started when I started using my files.

The command:
java -jar /home/dcharrance/VIC/target/VIC-1.0.1.jar -annotate_variation /home/dcharrance/annovar/annotate_variation.pl -b hg38 -convert2annovar /home/dcharrance/annovar/convert2annovar.pl -table_annovar /home/dcharrance/annovar/table_annovar.pl -d /home/dcharrance/annovar/humandb -db /home/dcharrance/VIC/vicdb -i gemelli.hg38_multianno.txt -input_type avinput -o gemelli.hg38_multianno.txt.

**Comment by maxh190** [comment]
Can you send your input dataset (gemelli.hg38_multianno.txt) that includes
one or two variants to me so that I can debug the possible issues in the
program?  If you worry about the data safety, you can change some of the
information, but keep the same format.  If you can do that, I will work on
it on the weekend.

**Comment by dcharrance** [comment]
I send you 10 lines of my input dataset (gemelli.hg38_multianno.txt). The name of the new file is inputvic.hg38_multianno.txt, same format of gemelli.hg38_multianno.txt.

Thanks you so much for your help.
Have a nice day

Debora
[inputvic.hg38_multianno.txt](https://github.com/HGLab/VIC/files/6083068/inputvic.hg38_multianno.txt)

**Comment by maxh190** [comment]
The file that you sent to me is not a vcf or avinput file.  Please read the
following lines on the page https://github.com/HGLab/VIC:

-i,--inputfile --required argument: The input file contains your variant

-input_type --required argument: The input file type, it can be
AVinput(Annovar's format),VCF(VCF with single sample),VCF_m(VCF with
multiple samples)

If I treated the file that you sent as an avinput file, VIC runs
without any problems.

**Comment by dcharrance** [comment]
Hi Max,
thank you for your answer!
Did you use the the same command like?

Thanks 
Debora

**Comment by maxh190** [comment]
Yes.  I recommend you using your VCF file as the input file.

Best,
Max
